default_agent: langgraph_claude_getting_started
agents:
  langgraph_claude_getting_started:
    name: langgraph_claude_getting_started
    entrypoint: C:/Maran/Study/Git/LangGraph/AmazonAgentCore/langgraph_bedrock.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::395109667422:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-2292fc8165
      execution_role_auto_create: false
      account: '395109667422'
      region: us-east-1
      ecr_repository: 395109667422.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-langgraph_claude_getting_started
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: langgraph_claude_getting_started-eT9HMDBC6H
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:395109667422:runtime/langgraph_claude_getting_started-eT9HMDBC6H
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-langgraph_claude_getting_started-builder
      execution_role: arn:aws:iam::395109667422:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-2292fc8165
      source_bucket: bedrock-agentcore-codebuild-sources-395109667422-us-east-1
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
